services:
  app:
    build:
      context: ./pagamento-app
      dockerfile: Dockerfile
    container_name: pagamento-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo

  db:
    image: mysql:latest
    container_name: pagamento-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pagamento
      MYSQL_USER: pagamento
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  
  mongo:
    image: mongo:7
    container_name: pagamento-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodata:/data/db

volumes:
  dbdata:
  mongodata:
